routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Categoria
    Route::delete('categoria/destroy', 'CategoriaController@massDestroy')->name('categoria.massDestroy');
    Route::resource('categoria', 'CategoriaController');

    // Departamento Medico
    Route::delete('departamento-medicos/destroy', 'DepartamentoMedicoController@massDestroy')->name('departamento-medicos.massDestroy');
    Route::resource('departamento-medicos', 'DepartamentoMedicoController');

    // Departamento
    Route::delete('departamentos/destroy', 'DepartamentoController@massDestroy')->name('departamentos.massDestroy');
    Route::resource('departamentos', 'DepartamentoController');

    // Marca
    Route::delete('marcas/destroy', 'MarcaController@massDestroy')->name('marcas.massDestroy');
    Route::resource('marcas', 'MarcaController');

    // Medico
    Route::delete('medicos/destroy', 'MedicoController@massDestroy')->name('medicos.massDestroy');
    Route::resource('medicos', 'MedicoController');

    // Paciente
    Route::delete('pacientes/destroy', 'PacienteController@massDestroy')->name('pacientes.massDestroy');
    Route::resource('pacientes', 'PacienteController');

    // Cuenta
    Route::delete('cuenta/destroy', 'CuentaController@massDestroy')->name('cuenta.massDestroy');
    Route::resource('cuenta', 'CuentaController');

    // Medicamento
    Route::delete('medicamentos/destroy', 'MedicamentoController@massDestroy')->name('medicamentos.massDestroy');
    Route::resource('medicamentos', 'MedicamentoController');

    // Enfermera
    Route::delete('enfermeras/destroy', 'EnfermeraController@massDestroy')->name('enfermeras.massDestroy');
    Route::resource('enfermeras', 'EnfermeraController');

    // Cita
    Route::delete('cita/destroy', 'CitaController@massDestroy')->name('cita.massDestroy');
    Route::resource('cita', 'CitaController');

    // Recepcionista
    Route::delete('recepcionista/destroy', 'RecepcionistaController@massDestroy')->name('recepcionista.massDestroy');
    Route::resource('recepcionista', 'RecepcionistaController');

    // Farmacia
    Route::delete('farmacia/destroy', 'FarmaciaController@massDestroy')->name('farmacia.massDestroy');
    Route::resource('farmacia', 'FarmaciaController');

    // Casos De Paciente
    Route::delete('casos-de-pacientes/destroy', 'CasosDePacienteController@massDestroy')->name('casos-de-pacientes.massDestroy');
    Route::resource('casos-de-pacientes', 'CasosDePacienteController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Medicamento.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\Auditable;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Medicamento extends Model
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use Auditable;
    use HasFactory;

    public $table = 'medicamentos';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'categoria_id',
        'marca_id',
        'nombre',
        'precio_de_venta',
        'precio_de_compra',
        'composicion_de_sal',
        'descripcion',
        'efectos_colaterales',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_by_id',
    ];

    public function categoria()
    {
        return $this->belongsTo(Categorium::class, 'categoria_id');
    }

    public function marca()
    {
        return $this->belongsTo(Marca::class, 'marca_id');
    }

    public function created_by()
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/MedicamentoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyMedicamentoRequest;
use App\Http\Requests\StoreMedicamentoRequest;
use App\Http\Requests\UpdateMedicamentoRequest;
use App\Models\Categorium;
use App\Models\Marca;
use App\Models\Medicamento;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class MedicamentoController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('medicamento_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $medicamentos = Medicamento::with(['categoria', 'marca', 'created_by'])->get();

        return view('admin.medicamentos.index', compact('medicamentos'));
    }

    public function create()
    {
        abort_if(Gate::denies('medicamento_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categorias = Categorium::pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        $marcas = Marca::pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.medicamentos.create', compact('categorias', 'marcas'));
    }

    public function store(StoreMedicamentoRequest $request)
    {
        $medicamento = Medicamento::create($request->all());

        return redirect()->route('admin.medicamentos.index');
    }

    public function edit(Medicamento $medicamento)
    {
        abort_if(Gate::denies('medicamento_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categorias = Categorium::pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        $marcas = Marca::pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        $medicamento->load('categoria', 'marca', 'created_by');

        return view('admin.medicamentos.edit', compact('categorias', 'marcas', 'medicamento'));
    }

    public function update(UpdateMedicamentoRequest $request, Medicamento $medicamento)
    {
        $medicamento->update($request->all());

        return redirect()->route('admin.medicamentos.index');
    }

    public function show(Medicamento $medicamento)
    {
        abort_if(Gate::denies('medicamento_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $medicamento->load('categoria', 'marca', 'created_by');

        return view('admin.medicamentos.show', compact('medicamento'));
    }

    public function destroy(Medicamento $medicamento)
    {
        abort_if(Gate::denies('medicamento_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $medicamento->delete();

        return back();
    }

    public function massDestroy(MassDestroyMedicamentoRequest $request)
    {
        Medicamento::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/medicamentos/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.create') }} {{ trans('cruds.medicamento.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.medicamentos.store") }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group {{ $errors->has('categoria') ? 'has-error' : '' }}">
                            <label class="required" for="categoria_id">{{ trans('cruds.medicamento.fields.categoria') }}</label>
                            <select class="form-control select2" name="categoria_id" id="categoria_id" required>
                                @foreach($categorias as $id => $entry)
                                    <option value="{{ $id }}" {{ old('categoria_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('categoria'))
                                <span class="help-block" role="alert">{{ $errors->first('categoria') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.categoria_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('marca') ? 'has-error' : '' }}">
                            <label class="required" for="marca_id">{{ trans('cruds.medicamento.fields.marca') }}</label>
                            <select class="form-control select2" name="marca_id" id="marca_id" required>
                                @foreach($marcas as $id => $entry)
                                    <option value="{{ $id }}" {{ old('marca_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('marca'))
                                <span class="help-block" role="alert">{{ $errors->first('marca') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.marca_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('nombre') ? 'has-error' : '' }}">
                            <label class="required" for="nombre">{{ trans('cruds.medicamento.fields.nombre') }}</label>
                            <input class="form-control" type="text" name="nombre" id="nombre" value="{{ old('nombre', '') }}" required>
                            @if($errors->has('nombre'))
                                <span class="help-block" role="alert">{{ $errors->first('nombre') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.nombre_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('precio_de_venta') ? 'has-error' : '' }}">
                            <label class="required" for="precio_de_venta">{{ trans('cruds.medicamento.fields.precio_de_venta') }}</label>
                            <input class="form-control" type="number" name="precio_de_venta" id="precio_de_venta" value="{{ old('precio_de_venta', '') }}" step="0.01" required>
                            @if($errors->has('precio_de_venta'))
                                <span class="help-block" role="alert">{{ $errors->first('precio_de_venta') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.precio_de_venta_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('precio_de_compra') ? 'has-error' : '' }}">
                            <label class="required" for="precio_de_compra">{{ trans('cruds.medicamento.fields.precio_de_compra') }}</label>
                            <input class="form-control" type="number" name="precio_de_compra" id="precio_de_compra" value="{{ old('precio_de_compra', '') }}" step="0.01" required>
                            @if($errors->has('precio_de_compra'))
                                <span class="help-block" role="alert">{{ $errors->first('precio_de_compra') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.precio_de_compra_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('composicion_de_sal') ? 'has-error' : '' }}">
                            <label class="required" for="composicion_de_sal">{{ trans('cruds.medicamento.fields.composicion_de_sal') }}</label>
                            <input class="form-control" type="text" name="composicion_de_sal" id="composicion_de_sal" value="{{ old('composicion_de_sal', '') }}" required>
                            @if($errors->has('composicion_de_sal'))
                                <span class="help-block" role="alert">{{ $errors->first('composicion_de_sal') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.composicion_de_sal_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('descripcion') ? 'has-error' : '' }}">
                            <label for="descripcion">{{ trans('cruds.medicamento.fields.descripcion') }}</label>
                            <textarea class="form-control" name="descripcion" id="descripcion">{{ old('descripcion') }}</textarea>
                            @if($errors->has('descripcion'))
                                <span class="help-block" role="alert">{{ $errors->first('descripcion') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.descripcion_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('efectos_colaterales') ? 'has-error' : '' }}">
                            <label for="efectos_colaterales">{{ trans('cruds.medicamento.fields.efectos_colaterales') }}</label>
                            <textarea class="form-control" name="efectos_colaterales" id="efectos_colaterales">{{ old('efectos_colaterales') }}</textarea>
                            @if($errors->has('efectos_colaterales'))
                                <span class="help-block" role="alert">{{ $errors->first('efectos_colaterales') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.efectos_colaterales_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/medicamentos/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.edit') }} {{ trans('cruds.medicamento.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.medicamentos.update", [$medicamento->id]) }}" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group {{ $errors->has('categoria') ? 'has-error' : '' }}">
                            <label class="required" for="categoria_id">{{ trans('cruds.medicamento.fields.categoria') }}</label>
                            <select class="form-control select2" name="categoria_id" id="categoria_id" required>
                                @foreach($categorias as $id => $entry)
                                    <option value="{{ $id }}" {{ (old('categoria_id') ? old('categoria_id') : $medicamento->categoria->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('categoria'))
                                <span class="help-block" role="alert">{{ $errors->first('categoria') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.categoria_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('marca') ? 'has-error' : '' }}">
                            <label class="required" for="marca_id">{{ trans('cruds.medicamento.fields.marca') }}</label>
                            <select class="form-control select2" name="marca_id" id="marca_id" required>
                                @foreach($marcas as $id => $entry)
                                    <option value="{{ $id }}" {{ (old('marca_id') ? old('marca_id') : $medicamento->marca->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('marca'))
                                <span class="help-block" role="alert">{{ $errors->first('marca') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.marca_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('nombre') ? 'has-error' : '' }}">
                            <label class="required" for="nombre">{{ trans('cruds.medicamento.fields.nombre') }}</label>
                            <input class="form-control" type="text" name="nombre" id="nombre" value="{{ old('nombre', $medicamento->nombre) }}" required>
                            @if($errors->has('nombre'))
                                <span class="help-block" role="alert">{{ $errors->first('nombre') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.nombre_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('precio_de_venta') ? 'has-error' : '' }}">
                            <label class="required" for="precio_de_venta">{{ trans('cruds.medicamento.fields.precio_de_venta') }}</label>
                            <input class="form-control" type="number" name="precio_de_venta" id="precio_de_venta" value="{{ old('precio_de_venta', $medicamento->precio_de_venta) }}" step="0.01" required>
                            @if($errors->has('precio_de_venta'))
                                <span class="help-block" role="alert">{{ $errors->first('precio_de_venta') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.precio_de_venta_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('precio_de_compra') ? 'has-error' : '' }}">
                            <label class="required" for="precio_de_compra">{{ trans('cruds.medicamento.fields.precio_de_compra') }}</label>
                            <input class="form-control" type="number" name="precio_de_compra" id="precio_de_compra" value="{{ old('precio_de_compra', $medicamento->precio_de_compra) }}" step="0.01" required>
                            @if($errors->has('precio_de_compra'))
                                <span class="help-block" role="alert">{{ $errors->first('precio_de_compra') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.precio_de_compra_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('composicion_de_sal') ? 'has-error' : '' }}">
                            <label class="required" for="composicion_de_sal">{{ trans('cruds.medicamento.fields.composicion_de_sal') }}</label>
                            <input class="form-control" type="text" name="composicion_de_sal" id="composicion_de_sal" value="{{ old('composicion_de_sal', $medicamento->composicion_de_sal) }}" required>
                            @if($errors->has('composicion_de_sal'))
                                <span class="help-block" role="alert">{{ $errors->first('composicion_de_sal') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.composicion_de_sal_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('descripcion') ? 'has-error' : '' }}">
                            <label for="descripcion">{{ trans('cruds.medicamento.fields.descripcion') }}</label>
                            <textarea class="form-control" name="descripcion" id="descripcion">{{ old('descripcion', $medicamento->descripcion) }}</textarea>
                            @if($errors->has('descripcion'))
                                <span class="help-block" role="alert">{{ $errors->first('descripcion') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.descripcion_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('efectos_colaterales') ? 'has-error' : '' }}">
                            <label for="efectos_colaterales">{{ trans('cruds.medicamento.fields.efectos_colaterales') }}</label>
                            <textarea class="form-control" name="efectos_colaterales" id="efectos_colaterales">{{ old('efectos_colaterales', $medicamento->efectos_colaterales) }}</textarea>
                            @if($errors->has('efectos_colaterales'))
                                <span class="help-block" role="alert">{{ $errors->first('efectos_colaterales') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medicamento.fields.efectos_colaterales_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/medicamentos/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    @can('medicamento_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route('admin.medicamentos.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.medicamento.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('cruds.medicamento.title_singular') }} {{ trans('global.list') }}
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-Medicamento">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.id') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.categoria') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.marca') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.nombre') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.precio_de_venta') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.precio_de_compra') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.composicion_de_sal') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.descripcion') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.efectos_colaterales') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($medicamentos as $key => $medicamento)
                                    <tr data-entry-id="{{ $medicamento->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $medicamento->id ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->categoria->nombre ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->marca->nombre ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->nombre ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->precio_de_venta ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->precio_de_compra ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->composicion_de_sal ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->descripcion ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->efectos_colaterales ?? '' }}
                                        </td>
                                        <td>
                                            @can('medicamento_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('admin.medicamentos.show', $medicamento->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan

                                            @can('medicamento_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.medicamentos.edit', $medicamento->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('medicamento_delete')
                                                <form action="{{ route('admin.medicamentos.destroy', $medicamento->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('medicamento_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.medicamentos.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Medicamento:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection