routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Categoria
    Route::delete('categoria/destroy', 'CategoriaController@massDestroy')->name('categoria.massDestroy');
    Route::resource('categoria', 'CategoriaController');

    // Departamento Medico
    Route::delete('departamento-medicos/destroy', 'DepartamentoMedicoController@massDestroy')->name('departamento-medicos.massDestroy');
    Route::resource('departamento-medicos', 'DepartamentoMedicoController');

    // Departamento
    Route::delete('departamentos/destroy', 'DepartamentoController@massDestroy')->name('departamentos.massDestroy');
    Route::resource('departamentos', 'DepartamentoController');

    // Marca
    Route::delete('marcas/destroy', 'MarcaController@massDestroy')->name('marcas.massDestroy');
    Route::resource('marcas', 'MarcaController');

    // Medico
    Route::delete('medicos/destroy', 'MedicoController@massDestroy')->name('medicos.massDestroy');
    Route::resource('medicos', 'MedicoController');

    // Paciente
    Route::delete('pacientes/destroy', 'PacienteController@massDestroy')->name('pacientes.massDestroy');
    Route::resource('pacientes', 'PacienteController');

    // Cuenta
    Route::delete('cuenta/destroy', 'CuentaController@massDestroy')->name('cuenta.massDestroy');
    Route::resource('cuenta', 'CuentaController');

    // Medicamento
    Route::delete('medicamentos/destroy', 'MedicamentoController@massDestroy')->name('medicamentos.massDestroy');
    Route::resource('medicamentos', 'MedicamentoController');

    // Enfermera
    Route::delete('enfermeras/destroy', 'EnfermeraController@massDestroy')->name('enfermeras.massDestroy');
    Route::resource('enfermeras', 'EnfermeraController');

    // Cita
    Route::delete('cita/destroy', 'CitaController@massDestroy')->name('cita.massDestroy');
    Route::resource('cita', 'CitaController');

    // Recepcionista
    Route::delete('recepcionista/destroy', 'RecepcionistaController@massDestroy')->name('recepcionista.massDestroy');
    Route::resource('recepcionista', 'RecepcionistaController');

    // Farmacia
    Route::delete('farmacia/destroy', 'FarmaciaController@massDestroy')->name('farmacia.massDestroy');
    Route::resource('farmacia', 'FarmaciaController');

    // Casos De Paciente
    Route::delete('casos-de-pacientes/destroy', 'CasosDePacienteController@massDestroy')->name('casos-de-pacientes.massDestroy');
    Route::resource('casos-de-pacientes', 'CasosDePacienteController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Marca.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\Auditable;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Marca extends Model
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use Auditable;
    use HasFactory;

    public $table = 'marcas';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'nombre',
        'correo_electronico',
        'telefono',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_by_id',
    ];

    public function marcaMedicamentos()
    {
        return $this->hasMany(Medicamento::class, 'marca_id', 'id');
    }

    public function created_by()
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/MarcaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyMarcaRequest;
use App\Http\Requests\StoreMarcaRequest;
use App\Http\Requests\UpdateMarcaRequest;
use App\Models\Marca;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class MarcaController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('marca_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $marcas = Marca::with(['created_by'])->get();

        return view('admin.marcas.index', compact('marcas'));
    }

    public function create()
    {
        abort_if(Gate::denies('marca_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.marcas.create');
    }

    public function store(StoreMarcaRequest $request)
    {
        $marca = Marca::create($request->all());

        return redirect()->route('admin.marcas.index');
    }

    public function edit(Marca $marca)
    {
        abort_if(Gate::denies('marca_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $marca->load('created_by');

        return view('admin.marcas.edit', compact('marca'));
    }

    public function update(UpdateMarcaRequest $request, Marca $marca)
    {
        $marca->update($request->all());

        return redirect()->route('admin.marcas.index');
    }

    public function show(Marca $marca)
    {
        abort_if(Gate::denies('marca_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $marca->load('created_by', 'marcaMedicamentos');

        return view('admin.marcas.show', compact('marca'));
    }

    public function destroy(Marca $marca)
    {
        abort_if(Gate::denies('marca_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $marca->delete();

        return back();
    }

    public function massDestroy(MassDestroyMarcaRequest $request)
    {
        Marca::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/marcas/relationships/marcaMedicamentos.blade.php
<div class="content">
    @can('medicamento_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route('admin.medicamentos.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.medicamento.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('cruds.medicamento.title_singular') }} {{ trans('global.list') }}
                </div>
                <div class="panel-body">

                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-marcaMedicamentos">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.id') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.categoria') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.marca') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.nombre') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.precio_de_venta') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.precio_de_compra') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.composicion_de_sal') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.descripcion') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medicamento.fields.efectos_colaterales') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($medicamentos as $key => $medicamento)
                                    <tr data-entry-id="{{ $medicamento->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $medicamento->id ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->categoria->nombre ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->marca->nombre ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->nombre ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->precio_de_venta ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->precio_de_compra ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->composicion_de_sal ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->descripcion ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medicamento->efectos_colaterales ?? '' }}
                                        </td>
                                        <td>
                                            @can('medicamento_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('admin.medicamentos.show', $medicamento->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan

                                            @can('medicamento_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.medicamentos.edit', $medicamento->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('medicamento_delete')
                                                <form action="{{ route('admin.medicamentos.destroy', $medicamento->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('medicamento_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.medicamentos.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-marcaMedicamentos:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection