routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Categoria
    Route::delete('categoria/destroy', 'CategoriaController@massDestroy')->name('categoria.massDestroy');
    Route::resource('categoria', 'CategoriaController');

    // Departamento Medico
    Route::delete('departamento-medicos/destroy', 'DepartamentoMedicoController@massDestroy')->name('departamento-medicos.massDestroy');
    Route::resource('departamento-medicos', 'DepartamentoMedicoController');

    // Departamento
    Route::delete('departamentos/destroy', 'DepartamentoController@massDestroy')->name('departamentos.massDestroy');
    Route::resource('departamentos', 'DepartamentoController');

    // Marca
    Route::delete('marcas/destroy', 'MarcaController@massDestroy')->name('marcas.massDestroy');
    Route::resource('marcas', 'MarcaController');

    // Medico
    Route::delete('medicos/destroy', 'MedicoController@massDestroy')->name('medicos.massDestroy');
    Route::resource('medicos', 'MedicoController');

    // Paciente
    Route::delete('pacientes/destroy', 'PacienteController@massDestroy')->name('pacientes.massDestroy');
    Route::resource('pacientes', 'PacienteController');

    // Cuenta
    Route::delete('cuenta/destroy', 'CuentaController@massDestroy')->name('cuenta.massDestroy');
    Route::resource('cuenta', 'CuentaController');

    // Medicamento
    Route::delete('medicamentos/destroy', 'MedicamentoController@massDestroy')->name('medicamentos.massDestroy');
    Route::resource('medicamentos', 'MedicamentoController');

    // Enfermera
    Route::delete('enfermeras/destroy', 'EnfermeraController@massDestroy')->name('enfermeras.massDestroy');
    Route::resource('enfermeras', 'EnfermeraController');

    // Cita
    Route::delete('cita/destroy', 'CitaController@massDestroy')->name('cita.massDestroy');
    Route::resource('cita', 'CitaController');

    // Recepcionista
    Route::delete('recepcionista/destroy', 'RecepcionistaController@massDestroy')->name('recepcionista.massDestroy');
    Route::resource('recepcionista', 'RecepcionistaController');

    // Farmacia
    Route::delete('farmacia/destroy', 'FarmaciaController@massDestroy')->name('farmacia.massDestroy');
    Route::resource('farmacia', 'FarmaciaController');

    // Casos De Paciente
    Route::delete('casos-de-pacientes/destroy', 'CasosDePacienteController@massDestroy')->name('casos-de-pacientes.massDestroy');
    Route::resource('casos-de-pacientes', 'CasosDePacienteController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Medico.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\Auditable;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Medico extends Model
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use Auditable;
    use HasFactory;

    public $table = 'medicos';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'usuario_id',
        'departamento_medico_id',
        'especialista',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_by_id',
    ];

    public function medicoCita()
    {
        return $this->hasMany(Citum::class, 'medico_id', 'id');
    }

    public function usuario()
    {
        return $this->belongsTo(User::class, 'usuario_id');
    }

    public function departamento_medico()
    {
        return $this->belongsTo(DepartamentoMedico::class, 'departamento_medico_id');
    }

    public function created_by()
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/MedicoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyMedicoRequest;
use App\Http\Requests\StoreMedicoRequest;
use App\Http\Requests\UpdateMedicoRequest;
use App\Models\DepartamentoMedico;
use App\Models\Medico;
use App\Models\User;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class MedicoController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('medico_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $medicos = Medico::with(['usuario', 'departamento_medico', 'created_by'])->get();

        return view('admin.medicos.index', compact('medicos'));
    }

    public function create()
    {
        abort_if(Gate::denies('medico_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $usuarios = User::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $departamento_medicos = DepartamentoMedico::pluck('titulo', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.medicos.create', compact('usuarios', 'departamento_medicos'));
    }

    public function store(StoreMedicoRequest $request)
    {
        $medico = Medico::create($request->all());

        return redirect()->route('admin.medicos.index');
    }

    public function edit(Medico $medico)
    {
        abort_if(Gate::denies('medico_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $usuarios = User::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $departamento_medicos = DepartamentoMedico::pluck('titulo', 'id')->prepend(trans('global.pleaseSelect'), '');

        $medico->load('usuario', 'departamento_medico', 'created_by');

        return view('admin.medicos.edit', compact('usuarios', 'departamento_medicos', 'medico'));
    }

    public function update(UpdateMedicoRequest $request, Medico $medico)
    {
        $medico->update($request->all());

        return redirect()->route('admin.medicos.index');
    }

    public function show(Medico $medico)
    {
        abort_if(Gate::denies('medico_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $medico->load('usuario', 'departamento_medico', 'created_by', 'medicoCita');

        return view('admin.medicos.show', compact('medico'));
    }

    public function destroy(Medico $medico)
    {
        abort_if(Gate::denies('medico_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $medico->delete();

        return back();
    }

    public function massDestroy(MassDestroyMedicoRequest $request)
    {
        Medico::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/medicos/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.create') }} {{ trans('cruds.medico.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.medicos.store") }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group {{ $errors->has('usuario') ? 'has-error' : '' }}">
                            <label class="required" for="usuario_id">{{ trans('cruds.medico.fields.usuario') }}</label>
                            <select class="form-control select2" name="usuario_id" id="usuario_id" required>
                                @foreach($usuarios as $id => $entry)
                                    <option value="{{ $id }}" {{ old('usuario_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('usuario'))
                                <span class="help-block" role="alert">{{ $errors->first('usuario') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medico.fields.usuario_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('departamento_medico') ? 'has-error' : '' }}">
                            <label class="required" for="departamento_medico_id">{{ trans('cruds.medico.fields.departamento_medico') }}</label>
                            <select class="form-control select2" name="departamento_medico_id" id="departamento_medico_id" required>
                                @foreach($departamento_medicos as $id => $entry)
                                    <option value="{{ $id }}" {{ old('departamento_medico_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('departamento_medico'))
                                <span class="help-block" role="alert">{{ $errors->first('departamento_medico') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medico.fields.departamento_medico_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('especialista') ? 'has-error' : '' }}">
                            <label class="required" for="especialista">{{ trans('cruds.medico.fields.especialista') }}</label>
                            <input class="form-control" type="text" name="especialista" id="especialista" value="{{ old('especialista', '') }}" required>
                            @if($errors->has('especialista'))
                                <span class="help-block" role="alert">{{ $errors->first('especialista') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medico.fields.especialista_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/medicos/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.edit') }} {{ trans('cruds.medico.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.medicos.update", [$medico->id]) }}" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group {{ $errors->has('usuario') ? 'has-error' : '' }}">
                            <label class="required" for="usuario_id">{{ trans('cruds.medico.fields.usuario') }}</label>
                            <select class="form-control select2" name="usuario_id" id="usuario_id" required>
                                @foreach($usuarios as $id => $entry)
                                    <option value="{{ $id }}" {{ (old('usuario_id') ? old('usuario_id') : $medico->usuario->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('usuario'))
                                <span class="help-block" role="alert">{{ $errors->first('usuario') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medico.fields.usuario_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('departamento_medico') ? 'has-error' : '' }}">
                            <label class="required" for="departamento_medico_id">{{ trans('cruds.medico.fields.departamento_medico') }}</label>
                            <select class="form-control select2" name="departamento_medico_id" id="departamento_medico_id" required>
                                @foreach($departamento_medicos as $id => $entry)
                                    <option value="{{ $id }}" {{ (old('departamento_medico_id') ? old('departamento_medico_id') : $medico->departamento_medico->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('departamento_medico'))
                                <span class="help-block" role="alert">{{ $errors->first('departamento_medico') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medico.fields.departamento_medico_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('especialista') ? 'has-error' : '' }}">
                            <label class="required" for="especialista">{{ trans('cruds.medico.fields.especialista') }}</label>
                            <input class="form-control" type="text" name="especialista" id="especialista" value="{{ old('especialista', $medico->especialista) }}" required>
                            @if($errors->has('especialista'))
                                <span class="help-block" role="alert">{{ $errors->first('especialista') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.medico.fields.especialista_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/medicos/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    @can('medico_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route('admin.medicos.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.medico.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('cruds.medico.title_singular') }} {{ trans('global.list') }}
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-Medico">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        {{ trans('cruds.medico.fields.id') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medico.fields.usuario') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medico.fields.departamento_medico') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.medico.fields.especialista') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($medicos as $key => $medico)
                                    <tr data-entry-id="{{ $medico->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $medico->id ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medico->usuario->name ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medico->departamento_medico->titulo ?? '' }}
                                        </td>
                                        <td>
                                            {{ $medico->especialista ?? '' }}
                                        </td>
                                        <td>
                                            @can('medico_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('admin.medicos.show', $medico->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan

                                            @can('medico_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.medicos.edit', $medico->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('medico_delete')
                                                <form action="{{ route('admin.medicos.destroy', $medico->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('medico_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.medicos.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Medico:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/medicos/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.show') }} {{ trans('cruds.medico.title') }}
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.medicos.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                        <table class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                    <th>
                                        {{ trans('cruds.medico.fields.id') }}
                                    </th>
                                    <td>
                                        {{ $medico->id }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.medico.fields.usuario') }}
                                    </th>
                                    <td>
                                        {{ $medico->usuario->name ?? '' }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.medico.fields.departamento_medico') }}
                                    </th>
                                    <td>
                                        {{ $medico->departamento_medico->titulo ?? '' }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.medico.fields.especialista') }}
                                    </th>
                                    <td>
                                        {{ $medico->especialista }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.medicos.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.relatedData') }}
                </div>
                <ul class="nav nav-tabs" role="tablist" id="relationship-tabs">
                    <li role="presentation">
                        <a href="#medico_cita" aria-controls="medico_cita" role="tab" data-toggle="tab">
                            {{ trans('cruds.citum.title') }}
                        </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane" role="tabpanel" id="medico_cita">
                        @includeIf('admin.medicos.relationships.medicoCita', ['cita' => $medico->medicoCita])
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection