routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Categoria
    Route::delete('categoria/destroy', 'CategoriaController@massDestroy')->name('categoria.massDestroy');
    Route::resource('categoria', 'CategoriaController');

    // Departamento Medico
    Route::delete('departamento-medicos/destroy', 'DepartamentoMedicoController@massDestroy')->name('departamento-medicos.massDestroy');
    Route::resource('departamento-medicos', 'DepartamentoMedicoController');

    // Departamento
    Route::delete('departamentos/destroy', 'DepartamentoController@massDestroy')->name('departamentos.massDestroy');
    Route::resource('departamentos', 'DepartamentoController');

    // Marca
    Route::delete('marcas/destroy', 'MarcaController@massDestroy')->name('marcas.massDestroy');
    Route::resource('marcas', 'MarcaController');

    // Medico
    Route::delete('medicos/destroy', 'MedicoController@massDestroy')->name('medicos.massDestroy');
    Route::resource('medicos', 'MedicoController');

    // Paciente
    Route::delete('pacientes/destroy', 'PacienteController@massDestroy')->name('pacientes.massDestroy');
    Route::resource('pacientes', 'PacienteController');

    // Cuenta
    Route::delete('cuenta/destroy', 'CuentaController@massDestroy')->name('cuenta.massDestroy');
    Route::resource('cuenta', 'CuentaController');

    // Medicamento
    Route::delete('medicamentos/destroy', 'MedicamentoController@massDestroy')->name('medicamentos.massDestroy');
    Route::resource('medicamentos', 'MedicamentoController');

    // Enfermera
    Route::delete('enfermeras/destroy', 'EnfermeraController@massDestroy')->name('enfermeras.massDestroy');
    Route::resource('enfermeras', 'EnfermeraController');

    // Cita
    Route::delete('cita/destroy', 'CitaController@massDestroy')->name('cita.massDestroy');
    Route::resource('cita', 'CitaController');

    // Recepcionista
    Route::delete('recepcionista/destroy', 'RecepcionistaController@massDestroy')->name('recepcionista.massDestroy');
    Route::resource('recepcionista', 'RecepcionistaController');

    // Farmacia
    Route::delete('farmacia/destroy', 'FarmaciaController@massDestroy')->name('farmacia.massDestroy');
    Route::resource('farmacia', 'FarmaciaController');

    // Casos De Paciente
    Route::delete('casos-de-pacientes/destroy', 'CasosDePacienteController@massDestroy')->name('casos-de-pacientes.massDestroy');
    Route::resource('casos-de-pacientes', 'CasosDePacienteController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Http/Controllers/Admin/FarmaciaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyFarmaciumRequest;
use App\Http\Requests\StoreFarmaciumRequest;
use App\Http\Requests\UpdateFarmaciumRequest;
use App\Models\Farmacium;
use App\Models\User;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class FarmaciaController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('farmacium_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $farmacia = Farmacium::with(['usuario'])->get();

        return view('admin.farmacia.index', compact('farmacia'));
    }

    public function create()
    {
        abort_if(Gate::denies('farmacium_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $usuarios = User::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.farmacia.create', compact('usuarios'));
    }

    public function store(StoreFarmaciumRequest $request)
    {
        $farmacium = Farmacium::create($request->all());

        return redirect()->route('admin.farmacia.index');
    }

    public function edit(Farmacium $farmacium)
    {
        abort_if(Gate::denies('farmacium_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $usuarios = User::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $farmacium->load('usuario');

        return view('admin.farmacia.edit', compact('usuarios', 'farmacium'));
    }

    public function update(UpdateFarmaciumRequest $request, Farmacium $farmacium)
    {
        $farmacium->update($request->all());

        return redirect()->route('admin.farmacia.index');
    }

    public function show(Farmacium $farmacium)
    {
        abort_if(Gate::denies('farmacium_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $farmacium->load('usuario');

        return view('admin.farmacia.show', compact('farmacium'));
    }

    public function destroy(Farmacium $farmacium)
    {
        abort_if(Gate::denies('farmacium_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $farmacium->delete();

        return back();
    }

    public function massDestroy(MassDestroyFarmaciumRequest $request)
    {
        Farmacium::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/farmacia/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.create') }} {{ trans('cruds.farmacium.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.farmacia.store") }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group {{ $errors->has('usuario') ? 'has-error' : '' }}">
                            <label class="required" for="usuario_id">{{ trans('cruds.farmacium.fields.usuario') }}</label>
                            <select class="form-control select2" name="usuario_id" id="usuario_id" required>
                                @foreach($usuarios as $id => $entry)
                                    <option value="{{ $id }}" {{ old('usuario_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('usuario'))
                                <span class="help-block" role="alert">{{ $errors->first('usuario') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.farmacium.fields.usuario_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/farmacia/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.edit') }} {{ trans('cruds.farmacium.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.farmacia.update", [$farmacium->id]) }}" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group {{ $errors->has('usuario') ? 'has-error' : '' }}">
                            <label class="required" for="usuario_id">{{ trans('cruds.farmacium.fields.usuario') }}</label>
                            <select class="form-control select2" name="usuario_id" id="usuario_id" required>
                                @foreach($usuarios as $id => $entry)
                                    <option value="{{ $id }}" {{ (old('usuario_id') ? old('usuario_id') : $farmacium->usuario->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('usuario'))
                                <span class="help-block" role="alert">{{ $errors->first('usuario') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.farmacium.fields.usuario_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/farmacia/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    @can('farmacium_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route('admin.farmacia.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.farmacium.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('cruds.farmacium.title_singular') }} {{ trans('global.list') }}
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-Farmacium">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        {{ trans('cruds.farmacium.fields.id') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.farmacium.fields.usuario') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($farmacia as $key => $farmacium)
                                    <tr data-entry-id="{{ $farmacium->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $farmacium->id ?? '' }}
                                        </td>
                                        <td>
                                            {{ $farmacium->usuario->name ?? '' }}
                                        </td>
                                        <td>
                                            @can('farmacium_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('admin.farmacia.show', $farmacium->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan

                                            @can('farmacium_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.farmacia.edit', $farmacium->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('farmacium_delete')
                                                <form action="{{ route('admin.farmacia.destroy', $farmacium->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('farmacium_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.farmacia.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Farmacium:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/farmacia/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.show') }} {{ trans('cruds.farmacium.title') }}
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.farmacia.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                        <table class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                    <th>
                                        {{ trans('cruds.farmacium.fields.id') }}
                                    </th>
                                    <td>
                                        {{ $farmacium->id }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.farmacium.fields.usuario') }}
                                    </th>
                                    <td>
                                        {{ $farmacium->usuario->name ?? '' }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.farmacia.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection